#!/usr/bin/bash
# This script displays listening sockets along with the PID and name of the program.

netstat -lntu | awk 'NR>2 {print $4,$7}' | cut -d':' -f2- | sort -n | uniq -c | while read count port pid_program
do
    if [[ $pid_program != "-" ]]; then
        pid=$(echo $pid_program | cut -d'/' -f1)
        program=$(echo $pid_program | cut -d'/' -f2)
        echo "Port: $port is listening $count times by PID: $pid ($program)"
    fi
done

